### ISSUE TITLE
源码启动iotsharp，rabbit+mongo+influx 遥测数据写入influx失败

### ISSUE THREAD

**Issue by iioter** [IoTSharp/IoTSharp#586]
IoTSharp.Storage.InfluxDBStorage[0]
      4e587702-fc6e-4239-aac3-4d1df0681635数据处理失败Method not found: 'Void RestSharp.RestClient.set_UserAgent(System.String)'.
      System.MissingMethodException: Method not found: 'Void RestSharp.RestClient.set_UserAgent(System.String)'.
         at InfluxDB.Client.InfluxDBClient..ctor(InfluxDBClientOptions options)
         at InfluxDB.Client.InfluxDBClientFactory.Create(InfluxDBClientOptions options)
         at InfluxDB.Client.InfluxDBClientFactory.Create(String connectionString)
         at IoTSharp.Startup.<>c__DisplayClass5_0.<ConfigureServices>b__23() in D:\Repos\IoTSharp\IoTSharp\Startup.cs:line 267
         at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Create()
         at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Get()
         at IoTSharp.Storage.InfluxDBStorage.StoreTelemetryAsync(RawMsg msg) in D:\Repos\IoTSharp\IoTSharp\Storage\InfluxDBStorage.cs:line 236

**Comment by maikebing** [comment]
restsharp 的库问题， 降低到  106 版本解决。
